#!/bin/bash

# -f is set then overwrite existing files

paths=( "$HOME/.config/nvim" "$HOME/.tmux.conf" "$HOME/.zshrc" "$HOME/.xinitrc" "$HOME/.local/bin" )
force=0

usage() {
	echo "Usage: $0 [-f]"
	exit 1
}

force-usage() {
	echo "[dotfiles] Use -f to force overwrite."
	exit 1
}

if [ "$1" = "-f" ]; then
	force=1
	for path in "${paths[@]}"; do
		rm -rf "$path"
		echo "[dotfiles] $path removed."
	done
elif [ -n "$1" ]; then
	usage
fi

path_exists=0
for path in "${paths[@]}"; do
	if [ -e "$path" ]; then
		path_exists=1
		echo "[dotfiles] $path already exists."
		continue
	fi

	from="$(pwd)/${path#$HOME/}"
	to="$path"

	if [ -d "$to" ]; then
		ln -nfs "$from" "$to"
	fi
	ln -s "$from" "$to"

	echo "[dotfiles] $to -> $from"
done

if [ $path_exists -eq 1 ]; then
	force-usage
else
	echo "[dotfiles] files linked."
fi

git config --global core.editor "nvim"
git config --global user.name "Salman Sarray"
git config --global user.email "msal4@outlook.com"
git config --global init.defaultBranch main
git config --global pull.rebase false
echo "[git] configured."

